branch-defaults:
  default:
    environment: flask-env
    group_suffix: null
environment-defaults:
  lot-availibility-api:
    branch: null
    repository: null
global:
  application_name: lot-availibility-api
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: python-3.6
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
